"use client";

import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { Activity, ArchiveRestore, Box, ChevronRight, CircleStop, CloudCog, Cpu, FileCode2, FolderOpen, Gauge, HardDrive, LayoutDashboard, LogOut, Menu, Play, Plus, RotateCcw, Save, Server as ServerIcon, ShieldAlert, TerminalSquare, UsersRound, X, Zap } from "lucide-react";
import { api, authStore, baseUrl, type Server, type User } from "@/lib/api";

type View = "dashboard" | "servers" | "console" | "files" | "backups" | "nodes" | "admin";
type Dashboard = { totals: { totalServers: number; cpuPercent: number; ramUsedMb: number; storageUsedGb: number; online: number }; servers: Server[] };
type FileEntry = { name: string; path: string; isDirectory: boolean; sizeBytes: number; updatedAt: string };
const nav: Array<{ id: View; label: string; icon: typeof LayoutDashboard; admin?: boolean }> = [{ id: "dashboard", label: "Overview", icon: LayoutDashboard }, { id: "servers", label: "My servers", icon: ServerIcon }, { id: "console", label: "Live console", icon: TerminalSquare }, { id: "files", label: "File manager", icon: FolderOpen }, { id: "backups", label: "Backups", icon: ArchiveRestore }, { id: "nodes", label: "Runner nodes", icon: CloudCog, admin: true }, { id: "admin", label: "Admin center", icon: ShieldAlert, admin: true }];

export function ControlRoom() {
  const [user, setUser] = useState<User | null>(null); const [dashboard, setDashboard] = useState<Dashboard | null>(null); const [view, setView] = useState<View>("dashboard"); const [selectedId, setSelectedId] = useState<string>(); const [drawer, setDrawer] = useState(false); const [wizard, setWizard] = useState(false); const [notice, setNotice] = useState<string>();
  const refresh = async () => { try { const data = await api<Dashboard>("/v1/dashboard"); setDashboard(data); setSelectedId((current) => current && data.servers.some((server) => server.id === current) ? current : data.servers[0]?.id); } catch (error) { setNotice(error instanceof Error ? error.message : "Control plane unavailable."); } };
  useEffect(() => { const stored = window.localStorage.getItem("vc_user"); if (!authStore.get() || !stored) { window.location.href = "/login"; return; } setUser(JSON.parse(stored)); void refresh(); }, []);
  const selected = useMemo(() => dashboard?.servers.find((server) => server.id === selectedId), [dashboard, selectedId]);
  const logout = () => { authStore.clear(); window.localStorage.removeItem("vc_user"); window.location.href = "/"; };
  if (!user) return <main className="grain grid min-h-screen place-items-center"><div className="h-10 w-10 animate-spin rounded-full border-2 border-nebula border-t-transparent"/></main>;
  return <main className="grain gridline min-h-screen bg-ink text-slate-100"><aside className={`glass fixed inset-y-0 left-0 z-40 w-72 p-5 transition-transform lg:translate-x-0 ${drawer ? "translate-x-0" : "-translate-x-full"}`}><Brand/><div className="mt-9 space-y-1">{nav.filter((item) => !item.admin || user.role === "ADMIN").map((item) => <button key={item.id} onClick={() => { setView(item.id); setDrawer(false); }} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold transition ${view === item.id ? "bg-nebula text-white shadow-glow" : "text-slate-400 hover:bg-white/5 hover:text-white"}`}><item.icon size={18}/>{item.label}</button>)}</div><button onClick={logout} className="absolute bottom-6 left-5 flex items-center gap-3 text-sm font-semibold text-slate-400 hover:text-white"><LogOut size={18}/> Sign out</button></aside><div className="min-h-screen lg:pl-72"><header className="sticky top-0 z-30 flex items-center justify-between border-b border-white/10 bg-ink/80 px-5 py-4 backdrop-blur-xl sm:px-8"><button className="lg:hidden" onClick={() => setDrawer(true)}><Menu/></button><div className="hidden lg:block"><p className="text-xs font-bold uppercase tracking-[.18em] text-mint">Control plane</p><p className="mt-1 text-sm text-slate-400">Operate infrastructure without losing the pulse.</p></div><div className="flex items-center gap-3"><span className="hidden text-right text-sm sm:block"><b>{user.name ?? user.email}</b><br/><span className="text-xs text-slate-500">{user.role.toLowerCase()}</span></span><span className="grid h-9 w-9 place-items-center rounded-full bg-gradient-to-br from-nebula to-signal text-sm font-black">{(user.name ?? user.email)[0]?.toUpperCase()}</span><button onClick={() => setWizard(true)} className="inline-flex items-center gap-2 rounded-xl bg-nebula px-3 py-2 text-sm font-bold shadow-glow hover:bg-[#866eff]"><Plus size={16}/> <span className="hidden sm:inline">Create server</span></button></div></header><section className="mx-auto max-w-7xl px-5 py-7 sm:px-8"><AnimatePresence>{notice && <motion.div initial={{ opacity: 0, y: -8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }} className="mb-5 flex items-center justify-between rounded-2xl border border-amber-300/20 bg-amber-300/10 px-4 py-3 text-sm text-amber-100"><span>{notice}</span><button onClick={() => setNotice(undefined)}><X size={16}/></button></motion.div>}</AnimatePresence><ViewContent view={view} dashboard={dashboard} selected={selected} select={setSelectedId} refresh={refresh} user={user} notify={setNotice}/></section></div><AnimatePresence>{wizard && <ServerWizard close={() => setWizard(false)} complete={async () => { setWizard(false); await refresh(); setView("servers"); }} notify={setNotice}/>}</AnimatePresence>{drawer && <button aria-label="Close navigation" onClick={() => setDrawer(false)} className="fixed inset-0 z-30 bg-black/50 lg:hidden"/>}</main>;
}

function Brand() { return <div className="flex items-center gap-3 font-bold tracking-tight"><span className="grid h-10 w-10 place-items-center rounded-xl bg-nebula shadow-glow"><Box size={21}/></span><span>VirgoCloud<p className="mt-0.5 text-[10px] font-bold uppercase tracking-[.18em] text-mint">Dedicated control</p></span></div>; }

function ViewContent({ view, dashboard, selected, select, refresh, user, notify }: { view: View; dashboard: Dashboard | null; selected?: Server; select: (id: string) => void; refresh: () => Promise<void>; user: User; notify: (message: string) => void }) {
  if (!dashboard) return <div className="glass grid min-h-80 place-items-center rounded-3xl"><div className="text-center text-slate-400"><div className="mx-auto mb-4 h-9 w-9 animate-spin rounded-full border-2 border-nebula border-t-transparent"/>Loading infrastructure…</div></div>;
  if (view === "dashboard") return <Overview dashboard={dashboard} select={select} />;
  if (view === "servers") return <Servers servers={dashboard.servers} selected={selected} select={select} refresh={refresh} notify={notify}/>;
  if (view === "console") return <ConsolePanel server={selected} notify={notify}/>;
  if (view === "files") return <FileManager server={selected} notify={notify}/>;
  if (view === "backups") return <BackupManager server={selected} notify={notify}/>;
  if (view === "nodes") return <NodePanel notify={notify}/>;
  return <AdminPanel user={user} notify={notify}/>;
}

function Overview({ dashboard, select }: { dashboard: Dashboard; select: (id: string) => void }) { const metrics = [{ label: "Fleet servers", value: dashboard.totals.totalServers, icon: ServerIcon, tone: "text-nebula" }, { label: "Online now", value: dashboard.totals.online, icon: Activity, tone: "text-mint" }, { label: "RAM in use", value: `${(dashboard.totals.ramUsedMb / 1024).toFixed(1)} GB`, icon: Cpu, tone: "text-signal" }, { label: "Storage used", value: `${dashboard.totals.storageUsedGb.toFixed(1)} GB`, icon: HardDrive, tone: "text-amber-300" }]; return <div className="space-y-7"><div><p className="text-sm font-bold uppercase tracking-[.18em] text-mint">Fleet pulse</p><h1 className="mt-2 text-3xl font-black tracking-tight sm:text-4xl">Your Minecraft infrastructure</h1></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map((metric, index) => <motion.div key={metric.label} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * .05 }} className="glass rounded-2xl p-5"><metric.icon className={metric.tone} size={19}/><p className="mt-7 text-2xl font-black">{metric.value}</p><p className="mt-1 text-sm text-slate-400">{metric.label}</p></motion.div>)}</div><div className="glass rounded-3xl"><div className="flex items-center justify-between p-5 sm:p-6"><div><h2 className="font-bold">Active fleet</h2><p className="mt-1 text-sm text-slate-400">Live resource usage is collected from assigned runners.</p></div><Gauge className="text-mint"/></div>{dashboard.servers.length ? <div className="border-t border-white/10">{dashboard.servers.map((server) => <button key={server.id} onClick={() => select(server.id)} className="grid w-full grid-cols-[1fr_auto] items-center gap-4 border-b border-white/5 p-5 text-left last:border-b-0 hover:bg-white/[.03] sm:grid-cols-[1fr_120px_130px_32px]"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-white/5 text-mint"><ServerIcon size={17}/></span><span><b>{server.name}</b><small className="mt-1 block text-xs text-slate-500">{server.edition} · {server.version} · {server.node?.name ?? "pending runner"}</small></span></div><Status status={server.status}/><span className="hidden text-sm text-slate-400 sm:block">{server.metrics?.[0]?.playersOnline ?? 0}/{server.playerSlots} players</span><ChevronRight className="text-slate-500" size={18}/></button>)}</div> : <Empty icon={<ServerIcon/>} title="No servers yet" detail="Create your first Java or Bedrock server and assign it to an enrolled Docker runner."/>}</div></div>; }

function Servers({ servers, selected, select, refresh, notify }: { servers: Server[]; selected?: Server; select: (id: string) => void; refresh: () => Promise<void>; notify: (message: string) => void }) { return <div className="grid gap-6 xl:grid-cols-[.85fr_1.15fr]"><section className="glass rounded-3xl p-5"><p className="text-sm font-bold uppercase tracking-[.18em] text-mint">Servers</p><h1 className="mt-2 text-2xl font-black">Your worlds</h1><div className="mt-5 space-y-2">{servers.map((server) => <button onClick={() => select(server.id)} className={`w-full rounded-2xl p-4 text-left transition ${selected?.id === server.id ? "bg-nebula/25 ring-1 ring-nebula/60" : "bg-black/15 hover:bg-white/5"}`} key={server.id}><div className="flex items-center justify-between"><b>{server.name}</b><Status status={server.status}/></div><p className="mt-2 text-xs text-slate-400">{server.edition} · {server.software} · {server.ramMb} MB</p></button>)}</div></section><section className="glass rounded-3xl p-5 sm:p-7">{selected ? <><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-bold uppercase tracking-[.18em] text-mint">Server control</p><h2 className="mt-2 text-3xl font-black">{selected.name}</h2><p className="mt-1 text-sm text-slate-400">{selected.host ? `${selected.host}:${selected.port}` : "Runner assignment pending"}</p></div><Status status={selected.status}/></div><div className="mt-8 grid gap-3 sm:grid-cols-4"><Action label="Start" icon={<Play size={16}/>} action="start" server={selected} refresh={refresh} notify={notify}/><Action label="Stop" icon={<CircleStop size={16}/>} action="stop" server={selected} refresh={refresh} notify={notify}/><Action label="Restart" icon={<RotateCcw size={16}/>} action="restart" server={selected} refresh={refresh} notify={notify}/><Action label="Kill" icon={<Zap size={16}/>} action="kill" server={selected} refresh={refresh} notify={notify} danger/></div><div className="mt-8 grid gap-3 sm:grid-cols-3"><Info label="Version" value={selected.version}/><Info label="Allocation" value={`${selected.ramMb} MB`}/><Info label="Players" value={`${selected.metrics?.[0]?.playersOnline ?? 0}/${selected.playerSlots}`}/></div></> : <Empty icon={<ServerIcon/>} title="Select a server" detail="Choose a server from the fleet list to manage its lifecycle and performance."/>}</section></div>; }

function Action({ label, icon, action, server, refresh, notify, danger }: { label: string; icon: React.ReactNode; action: string; server: Server; refresh: () => Promise<void>; notify: (message: string) => void; danger?: boolean }) { const [busy, setBusy] = useState(false); const displayLabel = action === "start" ? (server.desiredState === "RUNNING" ? "Keep online" : "Start & keep online") : action === "stop" ? "Stop & disable" : label; const run = async () => { setBusy(true); try { await api(`/v1/servers/${server.id}/actions/${action}`, { method: "POST" }); await refresh(); } catch (error) { notify(error instanceof Error ? error.message : "Action failed."); } finally { setBusy(false); } }; return <button disabled={busy} onClick={run} title={action === "start" ? "Keeps this server running automatically after crashes and runner restarts." : action === "stop" ? "Stops the server and disables automatic restarting until you start it again." : undefined} className={`flex items-center justify-center gap-2 rounded-xl px-3 py-3 text-sm font-bold transition disabled:opacity-50 ${danger ? "border border-red-400/30 text-red-200 hover:bg-red-400/10" : "bg-white/7 hover:bg-white/12"}`}>{icon}{busy ? "Working" : displayLabel}</button>; }
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl border border-white/10 bg-black/15 p-4"><p className="text-xs font-bold uppercase tracking-[.15em] text-slate-500">{label}</p><p className="mt-2 font-bold">{value}</p></div>; }
function Status({ status }: { status: string }) { const online = status === "RUNNING"; return <span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[11px] font-bold ${online ? "bg-mint/10 text-mint" : status === "ERROR" ? "bg-red-400/10 text-red-200" : "bg-white/8 text-slate-400"}`}><i className={`h-1.5 w-1.5 rounded-full ${online ? "bg-mint" : "bg-current"}`}/>{status.toLowerCase()}</span>; }
function Empty({ icon, title, detail }: { icon: React.ReactNode; title: string; detail: string }) { return <div className="grid min-h-64 place-items-center p-8 text-center"><div><span className="mx-auto grid h-11 w-11 place-items-center rounded-2xl bg-white/5 text-nebula">{icon}</span><h3 className="mt-4 font-bold">{title}</h3><p className="mx-auto mt-2 max-w-sm text-sm leading-6 text-slate-400">{detail}</p></div></div>; }

function ConsolePanel({ server, notify }: { server?: Server; notify: (message: string) => void }) {
  const [lines, setLines] = useState<string[]>([]); const [command, setCommand] = useState(""); const socket = useRef<WebSocket | null>(null); const output = useRef<HTMLDivElement>(null);
  useEffect(() => { if (!server) return; const token = authStore.get(); const wsUrl = `${baseUrl.replace(/^http/, "ws")}/v1/servers/${server.id}/console?token=${encodeURIComponent(token ?? "")}`; const connection = new WebSocket(wsUrl); socket.current = connection; connection.onmessage = (event) => { try { const data = JSON.parse(event.data) as { line?: string; message?: string }; setLines((current) => [...current.slice(-299), data.line ?? data.message ?? ""]); } catch { /* dropped malformed console frame */ } }; connection.onerror = () => notify("Live console could not connect. Check runner reachability and browser origin settings."); return () => connection.close(); }, [server?.id]);
  useEffect(() => { output.current?.scrollTo({ top: output.current.scrollHeight }); }, [lines]);
  if (!server) return <Empty icon={<TerminalSquare/>} title="Select a server to open its console" detail="The console is authorized per server and proxied only to that server’s assigned runner container."/>;
  const send = (event: FormEvent) => { event.preventDefault(); if (!command.trim() || socket.current?.readyState !== WebSocket.OPEN) return; socket.current.send(JSON.stringify({ type: "command", command })); setLines((current) => [...current, `$ ${command}`]); setCommand(""); };
  return <div className="space-y-5"><div><p className="text-sm font-bold uppercase tracking-[.18em] text-mint">Live operations</p><h1 className="mt-2 text-3xl font-black">{server.name} console</h1></div><div className="glass overflow-hidden rounded-3xl"><div className="flex items-center justify-between border-b border-white/10 px-5 py-4"><span className="flex items-center gap-2 text-sm font-bold"><TerminalSquare size={17} className="text-mint"/> user@{server.name.toLowerCase().replace(/\s+/g, "-")}:~$</span><Status status={server.status}/></div><div ref={output} className="console-scroll h-[420px] overflow-auto bg-[#050711] p-5 font-mono text-xs leading-6 text-slate-300">{lines.length ? lines.map((line, index) => <p key={`${line}-${index}`} className={line.startsWith("$") ? "text-mint" : ""}>{line}</p>) : <p className="text-slate-500">Waiting for secure runner stream…</p>}</div><form onSubmit={send} className="flex gap-2 border-t border-white/10 p-3"><span className="pt-3 font-mono text-mint">›</span><input value={command} onChange={(event) => setCommand(event.target.value)} className="min-w-0 flex-1 bg-transparent px-1 py-2 font-mono text-sm outline-none" placeholder="/op player, ls, cat server.properties"/><button className="rounded-xl bg-nebula px-4 text-sm font-bold">Send</button></form></div><p className="rounded-2xl border border-mint/15 bg-mint/5 px-4 py-3 text-sm leading-6 text-slate-300">Minecraft commands begin with <code className="text-mint">/</code>. The scoped shell permits only inspection commands such as <code>ls</code>, <code>cat</code>, and <code>java -version</code>; use the file manager for edits.</p></div>;
}

function FileManager({ server, notify }: { server?: Server; notify: (message: string) => void }) {
  const [files, setFiles] = useState<FileEntry[]>([]); const [path, setPath] = useState(""); const [active, setActive] = useState<string>(); const [content, setContent] = useState(""); const [busy, setBusy] = useState(false);
  const load = async (nextPath = path) => { if (!server) return; setBusy(true); try { setFiles(await api<FileEntry[]>(`/v1/servers/${server.id}/files?path=${encodeURIComponent(nextPath)}`)); setPath(nextPath); setActive(undefined); } catch (error) { notify(error instanceof Error ? error.message : "Could not load server files."); } finally { setBusy(false); } };
  useEffect(() => { void load(""); }, [server?.id]);
  const open = async (file: FileEntry) => { if (file.isDirectory) return load(file.path); try { const response = await api<{ content: string }>(`/v1/servers/${server!.id}/file?path=${encodeURIComponent(file.path)}`); setActive(file.path); setContent(response.content); } catch (error) { notify(error instanceof Error ? error.message : "This file cannot be opened as text."); } };
  const save = async () => { if (!server || !active) return; setBusy(true); try { await api(`/v1/servers/${server.id}/file`, { method: "PUT", body: JSON.stringify({ path: active, content }) }); notify("File saved to the assigned server container."); } catch (error) { notify(error instanceof Error ? error.message : "File save failed."); } finally { setBusy(false); } };
  const upload = async (input: FileList | null) => { const file = input?.[0]; if (!server || !file) return; setBusy(true); try { const base64 = await asBase64(file); await api(`/v1/servers/${server.id}/upload`, { method: "POST", body: JSON.stringify({ path: path ? `${path}/${file.name}` : file.name, contentBase64: base64 }) }); await load(path); notify("Upload completed within the selected server’s data directory."); } catch (error) { notify(error instanceof Error ? error.message : "Upload failed."); } finally { setBusy(false); } };
  if (!server) return <Empty icon={<FolderOpen/>} title="Select a server to manage files" detail="All file requests are checked against the selected server owner and resolved only below that server’s data root."/>;
  return <div className="space-y-5"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-[.18em] text-mint">Scoped storage</p><h1 className="mt-2 text-3xl font-black">{server.name} files</h1></div><label className="cursor-pointer rounded-xl bg-nebula px-4 py-2 text-sm font-bold"><input onChange={(event) => void upload(event.target.files)} className="hidden" type="file"/>Upload file</label></div><div className="grid gap-5 xl:grid-cols-[.9fr_1.1fr]"><section onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); void upload(event.dataTransfer.files); }} className="glass rounded-3xl p-4"><div className="mb-4 flex items-center gap-2 text-sm text-slate-400"><button onClick={() => void load("")} className="hover:text-white">/data</button>{path && <><ChevronRight size={14}/><span>{path}</span></>}</div><button onClick={() => { const parts = path.split("/"); parts.pop(); void load(parts.join("/")); }} disabled={!path} className="mb-2 text-xs text-mint disabled:opacity-30">← Up one folder</button><div className="space-y-1">{files.map((file) => <button key={file.path} onClick={() => void open(file)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left hover:bg-white/5 ${active === file.path ? "bg-nebula/20" : ""}`}>{file.isDirectory ? <FolderOpen size={17} className="text-amber-300"/> : <FileCode2 size={17} className="text-signal"/>}<span className="min-w-0 flex-1 truncate text-sm font-semibold">{file.name}</span><span className="text-xs text-slate-500">{file.isDirectory ? "folder" : bytes(file.sizeBytes)}</span></button>)}</div>{!files.length && <p className="p-7 text-center text-sm text-slate-500">Drop a file here or upload it into this directory.</p>}</section><section className="glass flex min-h-[420px] flex-col rounded-3xl"><div className="flex items-center justify-between border-b border-white/10 px-4 py-3"><span className="truncate font-mono text-xs text-slate-400">{active ?? "Select a text config file"}</span><button disabled={!active || busy} onClick={() => void save()} className="inline-flex items-center gap-2 rounded-lg bg-nebula px-3 py-2 text-xs font-bold disabled:opacity-40"><Save size={14}/>Save</button></div><textarea spellCheck={false} value={content} onChange={(event) => setContent(event.target.value)} disabled={!active} className="min-h-[360px] flex-1 resize-none bg-transparent p-4 font-mono text-xs leading-6 outline-none disabled:opacity-40" placeholder="Open server.properties, a plugin configuration, or a mod configuration to edit it in-browser."/></section></div></div>;
}

function BackupManager({ server, notify }: { server?: Server; notify: (message: string) => void }) {
  const [data, setData] = useState<{ schedule?: { intervalHours: number; retentionCount: number }; backups: Array<{ id: string; sizeBytes: string | number; status: string; createdAt: string }> }>(); const [hours, setHours] = useState(6); const [retention, setRetention] = useState(7);
  const load = async () => { if (!server) return; try { const result = await api<typeof data>(`/v1/servers/${server.id}/backups`); setData(result); if (result?.schedule) { setHours(result.schedule.intervalHours); setRetention(result.schedule.retentionCount); } } catch (error) { notify(error instanceof Error ? error.message : "Could not load backup state."); } };
  useEffect(() => { void load(); }, [server?.id]);
  if (!server) return <Empty icon={<ArchiveRestore/>} title="Select a server to protect its world" detail="Backups are archived by the runner, uploaded directly to S3-compatible storage, and retained under the server’s configured policy."/>;
  const manual = async () => { try { await api(`/v1/servers/${server.id}/backups`, { method: "POST" }); notify("Backup queued. The runner will archive and upload the world to configured object storage."); await load(); } catch (error) { notify(error instanceof Error ? error.message : "Could not queue backup."); } };
  const schedule = async () => { try { await api(`/v1/servers/${server.id}/backups/schedule`, { method: "PUT", body: JSON.stringify({ intervalHours: hours, retentionCount: retention }) }); notify("Automatic backup schedule updated."); await load(); } catch (error) { notify(error instanceof Error ? error.message : "Schedule update failed."); } };
  return <div className="space-y-5"><div><p className="text-sm font-bold uppercase tracking-[.18em] text-mint">World resilience</p><h1 className="mt-2 text-3xl font-black">{server.name} backups</h1></div><div className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><section className="glass rounded-3xl p-5"><h2 className="font-bold">Automatic protection</h2><p className="mt-2 text-sm leading-6 text-slate-400">A dedicated worker submits a backup job to the assigned runner at your interval, then removes old metadata after retention cleanup.</p><label className="mt-5 block text-sm font-semibold">Every <input type="number" min={1} max={168} value={hours} onChange={(event) => setHours(Number(event.target.value))} className="mx-2 w-20 rounded-lg border border-white/10 bg-black/20 px-2 py-1.5 text-center"/> hours</label><label className="mt-4 block text-sm font-semibold">Keep <input type="number" min={1} max={100} value={retention} onChange={(event) => setRetention(Number(event.target.value))} className="mx-2 w-20 rounded-lg border border-white/10 bg-black/20 px-2 py-1.5 text-center"/> archives</label><div className="mt-6 flex gap-2"><button onClick={() => void schedule()} className="rounded-xl bg-nebula px-4 py-2.5 text-sm font-bold">Save schedule</button><button onClick={() => void manual()} className="rounded-xl border border-white/15 px-4 py-2.5 text-sm font-bold hover:bg-white/5">Back up now</button></div></section><section className="glass rounded-3xl"><div className="border-b border-white/10 p-5"><h2 className="font-bold">Archive history</h2></div>{data?.backups?.length ? data.backups.map((backup) => <div key={backup.id} className="flex items-center justify-between gap-4 border-b border-white/5 p-5 last:border-b-0"><div><p className="font-semibold">{new Date(backup.createdAt).toLocaleString()}</p><p className="mt-1 text-xs text-slate-500">{bytes(Number(backup.sizeBytes))} · {backup.status.toLowerCase()}</p></div><button onClick={async () => { try { await api(`/v1/servers/${server.id}/backups/${backup.id}/restore`, { method: "POST" }); notify("Restore has been handed to the runner. The server is stopped briefly to safely replace world files."); } catch (error) { notify(error instanceof Error ? error.message : "Restore failed."); } }} disabled={backup.status !== "AVAILABLE"} className="rounded-lg border border-white/15 px-3 py-2 text-xs font-bold hover:bg-white/5 disabled:opacity-30">Restore</button></div>) : <Empty icon={<ArchiveRestore/>} title="No archives yet" detail="Create a manual backup or save a schedule to begin protected world retention."/>}</section></div></div>;
}

function NodePanel({ notify }: { notify: (message: string) => void }) {
  const [nodes, setNodes] = useState<Array<{ id: string; name: string; type: string; status: string; cpuPercent: number; ramUsedMb: number; ramTotalMb: number; diskUsedGb: number; diskTotalGb: number; runningServers: number }>>([]); const [show, setShow] = useState(false); const [secret, setSecret] = useState<string>();
  const load = async () => { try { setNodes(await api("/v1/nodes")); } catch (error) { notify(error instanceof Error ? error.message : "Could not load nodes."); } };
  useEffect(() => { void load(); }, []);
  const enroll = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); try { const response = await api<{ enrollmentSecret: string }>("/v1/nodes", { method: "POST", body: JSON.stringify({ name: form.get("name"), type: form.get("type"), agentUrl: form.get("agentUrl"), region: form.get("region") || undefined }) }); setSecret(response.enrollmentSecret); await load(); } catch (error) { notify(error instanceof Error ? error.message : "Node enrollment failed."); } };
  return <div className="space-y-5"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-[.18em] text-mint">Cloud runners</p><h1 className="mt-2 text-3xl font-black">Node fleet</h1></div><button onClick={() => setShow(true)} className="rounded-xl bg-nebula px-4 py-2.5 text-sm font-bold">Enroll node</button></div><div className="grid gap-4 lg:grid-cols-2">{nodes.map((node) => <section key={node.id} className="glass rounded-3xl p-5"><div className="flex items-start justify-between"><div><h2 className="font-bold">{node.name}</h2><p className="mt-1 text-xs uppercase tracking-[.15em] text-slate-500">{node.type.replace("_", " ")}</p></div><Status status={node.status}/></div><div className="mt-6 grid grid-cols-3 gap-3"><Info label="CPU" value={`${node.cpuPercent.toFixed(0)}%`}/><Info label="RAM" value={`${(node.ramUsedMb / 1024).toFixed(1)}/${(node.ramTotalMb / 1024).toFixed(1)}G`}/><Info label="Servers" value={String(node.runningServers)}/></div></section>)}{!nodes.length && <div className="glass rounded-3xl lg:col-span-2"><Empty icon={<CloudCog/>} title="No runners enrolled" detail="Deploy the node-agent compose file to a Docker host, then enroll its HTTPS URL and add the generated secret to its environment."/></div>}</div><AnimatePresence>{show && <Modal title="Enroll Docker runner" close={() => setShow(false)}><form onSubmit={enroll} className="space-y-4"><Field label="Node name" name="name" placeholder="Mumbai runner 01"/><label className="block text-sm font-semibold">Node type<select name="type" className="mt-2 w-full rounded-xl border border-white/10 bg-ink px-3 py-2.5"><option value="DOCKER_HOST">Docker host</option><option value="LOCAL">Local machine</option><option value="CLOUD_VM">Cloud VM</option><option value="EXTERNAL">External node</option></select></label><Field label="Agent URL" name="agentUrl" type="url" placeholder="https://runner.example.com"/><Field label="Region" name="region" placeholder="ap-south-1" required={false}/><button className="w-full rounded-xl bg-nebula py-3 font-bold">Generate enrollment secret</button></form>{secret && <div className="mt-5 rounded-2xl border border-amber-300/25 bg-amber-300/10 p-4"><p className="text-sm font-bold text-amber-100">Copy this one-time node secret now</p><code className="mt-3 block break-all rounded-xl bg-black/30 p-3 text-xs text-mint">{secret}</code><p className="mt-3 text-xs leading-5 text-slate-400">Set it as <b>AGENT_SHARED_SECRET</b> on the runner along with the node ID. It is encrypted at rest and is not shown again.</p></div>}</Modal>}</AnimatePresence></div>;
}

function AdminPanel({ user, notify }: { user: User; notify: (message: string) => void }) {
  const [overview, setOverview] = useState<{ users: number; servers: number; nodes: Array<{ name: string; status: string; runningServers: number }>; recentLogs: Array<{ id: string; action: string; createdAt: string; actor?: { email: string }; server?: { name: string } }> }>();
  const [users, setUsers] = useState<Array<{ id: string; email: string; name?: string; role: string; _count: { servers: number }; limit?: { maxServers: number; maxRamMb: number; maxStorageGb: number } }>>([]);
  useEffect(() => { void (async () => { try { const [nextOverview, nextUsers] = await Promise.all([api<typeof overview>("/v1/admin/overview"), api<typeof users>("/v1/admin/users")]); setOverview(nextOverview); setUsers(nextUsers); } catch (error) { notify(error instanceof Error ? error.message : "Administrator data is unavailable."); } })(); }, []);
  return <div className="space-y-5"><div><p className="text-sm font-bold uppercase tracking-[.18em] text-mint">Administrator</p><h1 className="mt-2 text-3xl font-black">Infrastructure governance</h1></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Info label="Accounts" value={String(overview?.users ?? 0)}/><Info label="Provisioned servers" value={String(overview?.servers ?? 0)}/><Info label="Runner nodes" value={String(overview?.nodes.length ?? 0)}/><Info label="Your role" value={user.role}/></div><div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><section className="glass overflow-hidden rounded-3xl"><div className="border-b border-white/10 p-5"><h2 className="font-bold">User limits and abuse controls</h2><p className="mt-1 text-sm text-slate-400">Limits are evaluated before each new server is provisioned.</p></div><div className="divide-y divide-white/5">{users.map((member) => <div key={member.id} className="flex flex-wrap items-center justify-between gap-3 p-5"><div><p className="font-semibold">{member.name ?? member.email}</p><p className="mt-1 text-xs text-slate-500">{member.role} · {member._count.servers} servers · limit {member.limit?.maxServers ?? 3}</p></div><button onClick={async () => { const maxServers = Number(window.prompt("Maximum servers", String(member.limit?.maxServers ?? 3))); if (!Number.isFinite(maxServers)) return; try { await api(`/v1/admin/users/${member.id}/limits`, { method: "PUT", body: JSON.stringify({ maxServers, maxRamMb: member.limit?.maxRamMb ?? 8192, maxStorageGb: member.limit?.maxStorageGb ?? 20 }) }); notify("Server limit updated."); } catch (error) { notify(error instanceof Error ? error.message : "Limit update failed."); } }} className="rounded-lg border border-white/15 px-3 py-2 text-xs font-bold hover:bg-white/5">Edit limit</button></div>)}</div></section><section className="glass rounded-3xl"><div className="border-b border-white/10 p-5"><h2 className="font-bold">Audit stream</h2></div><div className="max-h-[420px] overflow-auto">{overview?.recentLogs.map((log) => <div key={log.id} className="border-b border-white/5 p-4"><p className="text-sm font-semibold">{log.action}</p><p className="mt-1 text-xs leading-5 text-slate-500">{log.actor?.email ?? "system"} · {log.server?.name ?? "platform"}<br/>{new Date(log.createdAt).toLocaleString()}</p></div>)}</div></section></div></div>;
}

function ServerWizard({ close, complete, notify }: { close: () => void; complete: () => Promise<void>; notify: (message: string) => void }) {
  const [edition, setEdition] = useState<"JAVA" | "BEDROCK">("JAVA"); const [busy, setBusy] = useState(false);
  const create = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setBusy(true); const form = new FormData(event.currentTarget); try { await api("/v1/servers", { method: "POST", body: JSON.stringify({ name: form.get("name"), edition, version: form.get("version"), software: form.get("software"), ramMb: Number(form.get("ramMb")), playerSlots: Number(form.get("playerSlots")), difficulty: form.get("difficulty"), gameMode: form.get("gameMode") }) }); await complete(); } catch (error) { notify(error instanceof Error ? error.message : "Server creation failed."); } finally { setBusy(false); } };
  return <Modal title="Create Minecraft server" close={close}><form onSubmit={create} className="space-y-4"><div className="grid grid-cols-2 gap-2">{(["JAVA", "BEDROCK"] as const).map((item) => <button type="button" key={item} onClick={() => setEdition(item)} className={`rounded-xl border p-3 text-sm font-bold ${edition === item ? "border-nebula bg-nebula/20" : "border-white/10 bg-white/5"}`}>{item === "JAVA" ? "Java Edition" : "Bedrock Edition"}</button>)}</div><Field label="Server name" name="name" placeholder="My survival world"/><div className="grid grid-cols-2 gap-3"><Field label="Version" name="version" defaultValue={edition === "JAVA" ? "1.21.4" : "1.21.70"}/><Field label="Software" name="software" defaultValue={edition === "JAVA" ? "PAPER" : "VANILLA"}/></div><div className="grid grid-cols-2 gap-3"><Field label="RAM (MB)" name="ramMb" type="number" defaultValue="4096"/><Field label="Player slots" name="playerSlots" type="number" defaultValue="20"/></div><div className="grid grid-cols-2 gap-3"><SelectField label="Difficulty" name="difficulty" values={["peaceful", "easy", "normal", "hard"]}/><SelectField label="Gamemode" name="gameMode" values={["survival", "creative", "adventure", "spectator"]}/></div><p className="rounded-xl border border-mint/15 bg-mint/5 p-3 text-xs leading-5 text-slate-300">Plugins are supported by selecting a compatible Java software type such as Paper. Mods can be uploaded to the server’s scoped <code>mods</code> directory after provisioning.</p><button disabled={busy} className="w-full rounded-xl bg-nebula py-3 font-bold disabled:opacity-60">{busy ? "Queueing provision…" : "Create server"}</button></form></Modal>;
}

function Modal({ title, close, children }: { title: string; close: () => void; children: React.ReactNode }) { return <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4" onMouseDown={close}><motion.div initial={{ opacity: 0, scale: .96, y: 12 }} animate={{ opacity: 1, scale: 1, y: 0 }} exit={{ opacity: 0, scale: .96 }} onMouseDown={(event) => event.stopPropagation()} className="glass max-h-[90vh] w-full max-w-xl overflow-auto rounded-3xl p-5 sm:p-7"><div className="mb-6 flex items-center justify-between"><h2 className="text-xl font-black">{title}</h2><button onClick={close} className="rounded-lg p-2 text-slate-400 hover:bg-white/10 hover:text-white"><X size={18}/></button></div>{children}</motion.div></motion.div>; }
function Field({ label, name, placeholder, type = "text", defaultValue, required = true }: { label: string; name: string; placeholder?: string; type?: string; defaultValue?: string; required?: boolean }) { return <label className="block text-sm font-semibold">{label}<input required={required} name={name} type={type} defaultValue={defaultValue} placeholder={placeholder} className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-3 py-2.5 outline-none ring-nebula focus:ring-2"/></label>; }
function SelectField({ label, name, values }: { label: string; name: string; values: string[] }) { return <label className="block text-sm font-semibold">{label}<select name={name} className="mt-2 w-full rounded-xl border border-white/10 bg-ink px-3 py-2.5">{values.map((value) => <option key={value} value={value}>{value}</option>)}</select></label>; }
function bytes(value: number) { return value > 1024 * 1024 ? `${(value / 1024 / 1024).toFixed(1)} MB` : value > 1024 ? `${(value / 1024).toFixed(1)} KB` : `${value} B`; }
function asBase64(file: File) { return new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onerror = () => reject(new Error("Could not read the selected file.")); reader.onload = () => resolve((reader.result as string).split(",")[1] ?? ""); reader.readAsDataURL(file); }); }
